name: Docker Build and Push
on:
  workflow_call:
    secrets:
      docker_hub_user:
        required: true
      docker_hub_password:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.docker_hub_user }}
        password: ${{ secrets.docker_hub_password }}
      
    - name: Set Docker image name
      id: set_image_name
      run: |
        OWNER_AND_REPO=${{ github.repository }}
        REPO_NAME=$(echo "$OWNER_AND_REPO" | cut -d'/' -f2)
        echo "IMAGE_NAME=${{ secrets.docker_hub_user }}/${REPO_NAME}:${{ github.ref_name }}-${{ github.sha }}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.set_image_name.outputs.IMAGE_NAME }}
